#messages to operation with exceptions
validateEmail: 'o e-mail está incorreto'
fieldnotfound: 'campo $+1 está incorreto, favor preencher'
validateCpf: 'O CPF está inválido'
CFUserBundle.user.fullname: 'O Nome não pode ficar em branco'
validateSenhaLen: 'O campo deve conter de $+1  até $+2 digitos'
CFUserBundle.UserEntity.stEmail.fieldnotfound: 'O campo $+1 está vazio'
CFUserBundle.UserEntity.stPassword.fieldnotfound: 'O campo $+1 está vazio'
validateSenha: 'a senha está incorreta, não pode ficar em branco e até 8 digitos'


# messages to operation request form
cfuserbundle.user.scenario.create.success: Cadastro efetuado com sucesso
cfuserbundle.user.scenario.create.error: 'Ocorreu algum problema ao cadastrar os dados, tente novamente'

#validate form of the login
cfuserbundle.user.scenario.login.error : 'E-mail ou senha incorreto, favor verificar.'


request.validate.error : 'Não encontrado o tipo $+1 definido no ManifestBundle'
request.validate.notauthorized: 'Permissão de acesso negada'
request.validate.method: 'Permissão de acesso negado, o verbo do método está incorreto'
request.validate.contentype: 'O tipo de entrada na requisição não está de acordo, por padrão para esse component deve se requisitar com o Content-Type $+1'














