(function(){var _ddplugin=function(){var self=this;this.initialized=false;this.callbackFunction=null;this.modernizrFilePath=window.cfclientPath+"CFIDE/cfclient/modernizr.custom.js";this.modernizrLoaded=false;this.matchmediaFilePath=window.cfclientPath+"CFIDE/cfclient/matchMedia.js";this.mediaQueryFileLoaded=false;this.bmaputilFilePath=window.cfclientPath+"CFIDE/cfclient/bmaputil.js";this.bmapFilePath=window.cfclientPath+"CFIDE/cfclient/bmap.js";this.probesFilePath=window.cfclientPath+"CFIDE/cfclient/probes.js";
this.devicegroupsFilePath=window.cfclientPath+"CFIDE/cfclient/devicegroups.js";this.browserMapLoaded=false;this.orientationCallBacks=new Array;this.resizeCallBacks=new Array;this.init=function(callback){if(self.initialized)return;self.initialized=true;self.callbackFunction=callback;cfclient.properties={};cfclient.loadJSFile(self.modernizrFilePath,function(){for(var i in Modernizr)cfclient.properties[i]=Modernizr[i];self.modernizrLoaded=true;self.libaryLoadedCallback()});cfclient.properties.width=
window.innerWidth;cfclient.properties.height=window.innerHeight;cfclient.properties.deviceWidth=window.screen.width;cfclient.properties.deviceHeight=window.screen.height;function handleOrientationValue(mql){if(mql.matches)cfclient.properties.orientation="portrait";else cfclient.properties.orientation="landscape";var is_ios=false;if(navigator.userAgent.match(/iPhone/i)||(navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)))is_ios=true;if(!is_ios){cfclient.properties.deviceWidth=
window.screen.width;cfclient.properties.deviceHeight=window.screen.height}else if(mql.matches){cfclient.properties.deviceWidth=window.screen.width;cfclient.properties.deviceHeight=window.screen.height}else{cfclient.properties.deviceWidth=window.screen.height;cfclient.properties.deviceHeight=window.screen.width}window.onresize=cfresize;for(var i in self.orientationCallBacks)if(self.orientationCallBacks.hasOwnProperty(i)){var orientCallBack=eval(i);var divStruct=self.orientationCallBacks[i];if(null!=
divStruct){globalDivStruct=divStruct;orientCallBack(cfclient.properties.orientation)}}}var resizeTimeout=100;function cfresize(){var onResize=function(){var is_ios=false;if(navigator.userAgent.match(/iPhone/i)||(navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)))is_ios=true;cfclient.properties.width=window.innerWidth;cfclient.properties.height=window.innerHeight;if(!is_ios){var tempOrientation="portrait";if(cfclient.properties.width>cfclient.properties.height)tempOrientation=
"landscape";if(tempOrientation!==cfclient.properties.orientation){cfclient.properties.orientation=tempOrientation;for(var i in self.orientationCallBacks)if(self.orientationCallBacks.hasOwnProperty(i)){var orientCallBack=eval(i);var divStruct=self.orientationCallBacks[i];if(null!=divStruct){globalDivStruct=divStruct;orientCallBack(cfclient.properties.orientation)}}}}for(var i in self.resizeCallBacks)if(self.resizeCallBacks.hasOwnProperty(i)){var resizeCallBack=eval(i);var divStruct=self.resizeCallBacks[i];
if(null!=divStruct){globalDivStruct=divStruct;resizeCallBack(cfclient.properties.width,cfclient.properties.height)}}window.onresize=cfresize};window.clearTimeout(resizeTimeout);resizeTimeout=window.setTimeout(onResize,100)}window.onresize=cfresize;function createOrientationListener(){var is_ios=false;if(navigator.userAgent.match(/iPhone/i)||(navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)))is_ios=true;if(is_ios){self.mediaQueryFileLoaded=true;if(typeof window.matchMedia!="undefined"){var portraitOrientationCheck=
window.matchMedia("(orientation: portrait)");portraitOrientationCheck.addListener(handleOrientationValue);handleOrientationValue(portraitOrientationCheck);self.libaryLoadedCallback()}else cfclient.loadJSFile(self.matchmediaFilePath,function(){var portraitOrientationCheck=mql("(orientation: portrait)",handleOrientationValue);handleOrientationValue(portraitOrientationCheck);self.libaryLoadedCallback()})}else{self.mediaQueryFileLoaded=true;window.onresize()}}createOrientationListener();cfclient.loadJSFile(self.bmaputilFilePath,
function(){cfclient.loadJSFile(self.bmapFilePath,function(){cfclient.loadJSFile(self.probesFilePath,function(){cfclient.loadJSFile(self.devicegroupsFilePath,function(){BrowserMap.forwardRequest();var matchedGroups=BrowserMap.getMatchedDeviceGroups();cfclient.properties.deviceGroupDescription=[];cfclient.properties.deviceGroupName=[];for(var g in matchedGroups){cfclient.properties.deviceGroupDescription.push(matchedGroups[g].description);cfclient.properties.deviceGroupName.push(matchedGroups[g].name)}self.browserMapLoaded=
true;self.libaryLoadedCallback()})})})})};this.libaryLoadedCallback=function(){if(self.callbackFunction!=null)if(self.mediaQueryFileLoaded&&(self.modernizrLoaded&&self.browserMapLoaded)){self.callbackFunction();self.callbackFunction=null}};this.addOrientationListener=function(listener){self.orientationCallBacks[listener.name]=globalDivStruct};this.removeOrientationListener=function(listener){for(var i in self.orientationCallBacks)if(i==listener.name){self.orientationCallBacks[i]=null;break}};this.addResizeListener=
function(listener){self.resizeCallBacks[listener.name]=globalDivStruct};this.removeResizeListener=function(listener){for(var i in self.resizeCallBacks)if(i==listener.name){self.resizeCallBacks[i]=null;break}}};window.cfclient_device_detection_plugin=new _ddplugin})();
