security:
    bundle_alias: user
    controller: credential

    role_hierarchy:
        - { ROLE_ANONYMOUS: IS_AUTHENTICATED_ANONYMOUSLY, balance: 0 }
        - { ROLE_USER: ROLE_USER, balance: 1 }
        - { ROLE_ADMIN: ROLE_ADMIN, balance: 2 }
        - { ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN, balance: 3 }
        - { ROLE_OAUTH : OAUTH, balance: 4 }

    # providers:
    #     cf_userbundle:
    #         id: CFUserBundle
    #         alias: user

    firewalls:
        # define access with not validation
        anonymous:    false
        # when action login
        root_path:   '?bundle=main'
        # when action logout
        path_login:  login

    ## definition to access of requests

    access_control_event:

        # define to front-end
        - { bundle: main,  event: main,        action: init,    role: [IS_AUTHENTICATED_ANONYMOUSLY] }
    
        # management API-REST

        ## Bundle CFUserBundle - define routes to credential of user
        - { bundle: user, event: credential,  action: login,    role: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_OAUTH] }
        - { bundle: user, event: credential,  action: create,   role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { bundle: user, event: credential,  action: logout,   role: [ROLE_USER] }
        - { bundle: user, event: rule,  action: list,   role: [ROLE_USER] }
        # - { bundle: user, event: credential,  action: edit,     role: [ROLE_ADMIN] }
        # - { bundle: user, event: credential,  action: init,     role: [ROLE_ADMIN] }
