security:
    bundle_alias: user
    controller: credential

    role_hierarchy:
        - { ROLE_ANONYMOUS: IS_AUTHENTICATED_ANONYMOUSLY, balance: 0 }
        - { ROLE_USER: ROLE_USER, balance: 1 }
        - { ROLE_ADMIN: ROLE_ADMIN, balance: 2 }
        - { ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN, balance: 3 }

    # providers:
    #     cf_userbundle:
    #         id: CFUserBundle
    #         alias: user

    firewalls:
        anonymous:    false
        route_main:   login

    ## definition to access of requests

    access_control_event:
        - { bundle: main,  event: main,        action: ActionInit,    role: [ROLE_USER] }
        - { bundle: main,  event: credential,  action: actionLogin,   role: [ROLE_USER] }



        ## Bundle CFUserBundle - define routes to credential of user
        - { bundle: user, event: credential,  action: login,    role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { bundle: user, event: credential,  action: create,   role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { bundle: user, event: credential,  action: init,     role: [ROLE_ADMIN] }
        - { bundle: user, event: credential,  action: edit,     role: [ROLE_ADMIN] }
