app:
  config: "Late afternoon is best. Backup contact is Nancy Billsmer @ 338-4338. "
  product:
    - !java.util.HashMap
      price: !java.lang.Double 450.0
      description: Basketball
      quantity: 4
      sku: BL394D
    - !java.util.HashMap
      price: !java.lang.Double 2392.0
      description: Super Hoop
      quantity: 1
      sku: BL4438H

